dbc_files:
 - bhz3.dbc
 - disp.dbc
 - eos7.dbc
can:
  interface: can0
  bitrate: 125000
mqtt:
  host: some_host_or_ip
  username: my_mqtt_user
  password: my_mqtt_password
send_to_can_from_topic: mqtt2can
name_conversion:
  first_underscores_to_slash: 2
